---
server:
  address: 0.0.0.0 # not used at this point, not sure it will be
  port: 8080
  endpoint: https://graph.geodex.org/blazegraph/namespace/cdf/sparql
  #endpoint: http://opencoredata.org/blazegraph/namespace/jrso/sparql
